name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - id:   cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key:  node-modules-cache-${{ hashFiles('package-lock.json') }}
      - if:  steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - id:   auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HEYPOINT_94E8E }}
          token_format:     access_token
      - run: npx nx run-many --target deploy --all
        env:
          APP_CHECK_TOKEN_HEYPOINT: ${{ secrets.APP_CHECK_TOKEN_HEYPOINT }}
          FIREBASE_TOKEN:           ${{ steps.auth.outputs.access_token }}
          NX_CLOUD_ACCESS_TOKEN:    ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
